### PR TITLE
add spool manager support

### PR DESCRIPTION
**Pull request by tduehr**
Adds basic support for SpoolManager.

### CODE REVIEW

**Comment by OllisGit** [comment]
PS. Sorry, for being late to the party, but I made a "Octoprint sabatical" (no coding, no printing) the last months.

**Comment by SM-26** [comment]
I've wanted to go ahead and test it.
tired to install from @tduehr branch (https://github.com/tduehr/OctoPrint-PrintJobHistory/archive/spoolManager.zip)

I can't activate the plugin now
image

**Comment by lightmaster** [comment]
Attempted to pull this using `https://github.com/OllisGit/OctoPrint-PrintJobHistory/archive/master.zip` and now OctoPrint refuses to enable this plugin.

**Comment by bullshit** [comment]
@lightmaster this could help #120

**Comment by lightmaster** [comment]
@bullshit Your fork at least enables for me. About to run a print with it, so I'll find out if the SpoolManager support works or not.

**Comment by lightmaster** [comment]
well that didn't go well, PrintJobHistory didn't save any Print Job at all.

**Comment by bullshit** [comment]
Thanks. I guess i could make a new branch based on the one which fixes the compile errors and start fixing the SpoolManager support.

I’m new to 3d printing and octoprint. Do you have any guidance how to quickly test PrintJobHistory code after a finished printjob? Is it enough to create a gcode file from a small object with a slicer and use the virtual printer and start a print?

**Comment by lightmaster** [comment]
@bullshit  Not saving history seems to be a different issue, unrelated to your patch: #118

**Comment by lightmaster** [comment]
Ok, got this to compile and save print histories now, however this PR still doesn't seem to do anything as far as Spool Manager is concerned.

**Pull request merged**
